name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: test
        run: |
          cp -r ./lib ./server/lib
          cp -r ./lib ./client/lib
          cd client && yarn install --production
          # TODO: Fix client tests
          # yarn test

          cd ../server && yarn install --production
          yarn test
          cd ..

      - name: build
        run: |
          # TODO: Improve
          backend_api=https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com
          sed -i -e 's/http:\/\/localhost:3000/${backend_api}/g' ./client/src/proxy.conf.json

          echo "proxy file was replaced. \n"
          cat ./client/src/proxy.conf.json

          cd client
          yarn build
          cp -r public ../server/assets/
          cp -r dist/ ../server/ng-build/

          cd ../server
          yarn build
          cd ..

      # - name: deploy
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
      #     heroku_email: ${{secrets.HEROKU_EMAIL}}
      #     usedocker: true
      #     appdir: 'server'
      #   env:
      #     NODE_ENV: production
      #     PORT: 8080
      #     SESSION_HOST: ${{ secrets.SESSION_HOST }}
      #     SESSION_PORT: ${{ secrets.SESSION_PORT }}
      #     SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      #     SESSION_MAX_AGE: ${{ secrets.SESSION_MAX_AGE }}
      #     SESSION_DISABLE: 1
